services:
  - type: web
    name: labeling-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar -Dspring.profiles.active=prod target/labeling_-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: FRONTEND_URL
        value: https://label-frontend-rho.vercel.app
    regions:
      - us-east-1
    plan: free  # or starter, standard, pro based on your needs 