services:
  - type: web
    name: labeling-backend
    env: docker
    healthCheckPath: /actuator/health
    envVars:
      - key: FRONTEND_URL
        value: http://label-frontend-rho.vercel.app  # Update this with your actual frontend URL when you deploy frontend
    plan: free 